### basics


In [1]:
import numpy as np

In [2]:
arr_id=np.array([1,2,3,4])
print("1D array: ",arr_id)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D array: ",arr_2d)


1D array:  [1 2 3 4]
2D array:  [[1 2 3]
 [4 5 6]]


### python list vs numpy array

In [4]:
py_list=[1,2,3]
print("python list multiplication :",py_list*2)

np_arr=np.array([1,2,3])
print("np array multiplication :",np_arr*2)

python list multiplication : [1, 2, 3, 1, 2, 3]
np array multiplication : [2 4 6]


In [10]:
zero=np.zeros((3,4))
print("Zeros :",zero)

one=np.ones((3,4))
print("ones :\n",one)

full=np.full((3,4),7)
print("full :\n",full)

r=np.random.random((3,4))
print(r)

seq=np.arange(0,10,2)
print("sequence :\n",seq)


Zeros : [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full :
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[0.23578034 0.24284285 0.18406391 0.88492226]
 [0.28459864 0.9894185  0.77129347 0.50615759]
 [0.6185183  0.534194   0.88420179 0.92553575]]
sequence :
 [0 2 4 6 8]


### Array property

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("Size: ",arr.size)
print("Dtype: ",arr.dtype)


Shape  (3, 3)
Dimension  2
Size  9
Dtype  int64


### Array reshaped

In [20]:
arr=np.arange(12)
print(arr)

reshape=arr.reshape((3,4))
print(reshape)

flat=reshape.flatten()
print(flat)

raval=reshape.ravel()
print(raval)

transpose=reshape.T
print(transpose)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Numpy array Operation

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Slicing :",arr[2:7])
print("With step :",arr[0:10:2])
print("Negative indexing :",arr[-3])

Slicing : [3 4 5 6 7]
With step : [1 3 5 7 9]
Negative indexing : 8


In [27]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific element :",a[1,2])
print("Entire row :",a[:,1])
print("Entire col :",a[1,:])

Specific element : 6
Entire row : [2 5 8]
Entire col : [4 5 6]


### Sorting

In [30]:
a1=np.array([14,2,15,89,6,3])
print("Sorted Array :",np.sort(a1))

a2=np.array([[8,9,4],[23,5,1],[48,2,0]])
print("Sorted 2d :",np.sort(a2))
print("Sorted by col:",np.sort(a2,axis=0))
print("Sorted by row:",np.sort(a2,axis=1))

Sorted Array : [ 2  3  6 14 15 89]
Sorted 2d : [[ 4  8  9]
 [ 1  5 23]
 [ 0  2 48]]
Sorted by col: [[ 8  2  0]
 [23  5  1]
 [48  9  4]]
Sorted by row: [[ 4  8  9]
 [ 1  5 23]
 [ 0  2 48]]


### filter

In [38]:
num=np.array([1,2,3,4,5,6,7,8,9,10])
print("Even num :",num[num%2==0])

mask=num>5
print("Even num by mask :",num[mask])

indices=[0,1,5]
print("arry by indices :",num[indices])

condition=np.where(num>5, num*2,num)
print("Array condition :",condition)


Even num : [ 2  4  6  8 10]
Even num by mask : [ 6  7  8  9 10]
arry by indices : [1 2 6]
Array condition : [ 1  2  3  4  5 12 14 16 18 20]


### Adding and removing data

In [48]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,6,7,9,8])
combine=arr1+arr2
print(combine)
con=np.concatenate((arr1,arr2))
print(con)

ori=np.array([[1,2,3],[4,5,6],[7,8,9]])
new_r=np.array([[10,11,12]])
with_new=np.vstack((ori,new_r))
print("adding new row :",with_new)
new_c=np.array([[10],[11],[12]])
with_n=np.hstack((ori,new_c))
print("Addinf new col :",with_n)

dele=np.delete(ori,2)
print("Array after deletion ",dele)

[ 6  8 10 13 13]
[1 2 3 4 5 5 6 7 9 8]
adding new row : [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Addinf new col : [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
Array after deletion  [1 2 4 5 6 7 8 9]


In [1]:
import numpy as np


In [3]:
v1=np.array([1,2])

In [4]:
v2=np.array([3,4])

In [5]:
v3=v1+v2

In [6]:
v3

array([4, 6])

In [7]:
v4=v1*v2

In [8]:
v4

array([3, 8])

In [9]:
v4=2*v1

In [10]:
v4

array([2, 4])

In [3]:
a = np.array([1,0])
b = np.array([0,1])

A = np.column_stack([a,b])

print(np.linalg.matrix_rank(A))

2


In [2]:
import numpy as np

A = np.array([
    [2,1],
    [0,1]
])

v = np.array([3,2])

print(A @ v)

[8 2]


In [3]:
A = np.array([[1,0],
              [1,1]])

B = np.array([[2,0],
              [0,1]])

print(A @ B)

[[2 0]
 [2 1]]


In [4]:
import numpy as np

A = np.array([[2,0],
              [0,3]])

print(np.linalg.det(A))

6.0
